### ISSUE TITLE
Release 1.4.6 does not contain arm64 architecture

### ISSUE THREAD

**Issue by ReOuJneD** [chartbeat-labs/chartbeat-ios-sdk#13]
Same issue as with Release 1.4.3

**Comment by Maxatma** [comment]
same as 1.4.7

**Comment by joshschwartz** [comment]
Thank you for this report. We are looking into it and will follow up.

**Comment by XIWEI-house** [comment]
verision 1.4.8 is published which should resolve issue above. Thank you!

**Comment by Maxatma** [comment]
@XIWEI-house @joshschwartz don't want to disappoint you, but probably 1.4.8 still didn't help
Still have:
`Undefined symbol: _OBJC_CLASS_$_CBTracker` issue 

this [issue](https://github.com/chartbeat-labs/chartbeat-ios-sdk/issues/9 ) also refers to a similar (or the same) problem: 

This is what I have for 1.4.8 version 
![Screen Shot 2021-07-28 at 03 26 24](https://user-images.githubusercontent.com/7135226/127244639-90d45432-997c-451c-90ae-019bee8ff876.png)
![Screen Shot 2021-07-28 at 03 26 32](https://user-images.githubusercontent.com/7135226/127244643-41504d0d-01a4-49d1-8edb-25d85eda1b72.png)

**Comment by XIWEI-house** [comment]
Thank you for the note Maxtma! Could you provide a bit more info on which xcode version and which device (physical device or simulator) are you using? Since which version did you see the error above? Thank you!

**Comment by XIWEI-house** [comment]
Just pushed version 1.4.9, that should solve “missing required architecture arm64” issue. Thank you!
