### ISSUE TITLE
Fix deprecation warnings

### ISSUE THREAD

**Issue by fredhdroz** [chartbeat-labs/chartbeat-ios-sdk#2]
Compilation shows multiple deprecation warnings : 'MPMoviePlayerController' is deprecated: first deprecated in iOS 9.0 

-[MediaPlayerTracker  initWithMediaPlayer:(MPMoviePlayerController *)movieController_ title:(NSString *)title_ thumbnail:(NSString *)thumbnail_]

**Comment by dgdempster** [comment]
We have added this locally to MediaPlayerTracker.h, ideally should be pulled back into the project.

#if __IPHONE_OS_VERSION_MIN_REQUIRED < 90000
- (id)initWithMediaPlayer:(MPMoviePlayerController *)movieController_ title:(NSString *)title_ thumbnail:(NSString *)thumbnail_;
#endif

**Comment by joshschwartz** [comment]
Apologies for the very, very delayed response here! This has been resolved in 1.4.7.
